// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/story.proto

package story

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for a story segment.
type StorySegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`        // Unique segment ID.
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`    // The story text.
	Votes         int32                  `protobuf:"varint,3,opt,name=votes,proto3" json:"votes,omitempty"` // Votes for this segment.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorySegment) Reset() {
	*x = StorySegment{}
	mi := &file_proto_story_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorySegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorySegment) ProtoMessage() {}

func (x *StorySegment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorySegment.ProtoReflect.Descriptor instead.
func (*StorySegment) Descriptor() ([]byte, []int) {
	return file_proto_story_proto_rawDescGZIP(), []int{0}
}

func (x *StorySegment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StorySegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *StorySegment) GetVotes() int32 {
	if x != nil {
		return x.Votes
	}
	return 0
}

// Request for generating a new segment.
type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"` // User-provided prompt.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_proto_story_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

// Response for generated segment.
type GenerateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedText string                 `protobuf:"bytes,1,opt,name=generated_text,json=generatedText,proto3" json:"generated_text,omitempty"` // Text generated by the AI.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_proto_story_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateResponse) GetGeneratedText() string {
	if x != nil {
		return x.GeneratedText
	}
	return ""
}

// Message for real-time updates.
type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"` // ID of the story.
	Segment       *StorySegment          `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`                // New segment data.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_proto_story_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_story_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *UpdateRequest) GetSegment() *StorySegment {
	if x != nil {
		return x.Segment
	}
	return nil
}

// Streaming response for collaborative updates.
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*StorySegment        `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"` // List of current segments.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_proto_story_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_story_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_story_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateResponse) GetSegments() []*StorySegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

var File_proto_story_proto protoreflect.FileDescriptor

const file_proto_story_proto_rawDesc = "" +
	"\n" +
	"\x11proto/story.proto\x12\x05story\x1a\x1bgoogle/protobuf/empty.proto\"H\n" +
	"\fStorySegment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x14\n" +
	"\x05votes\x18\x03 \x01(\x05R\x05votes\")\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"9\n" +
	"\x10GenerateResponse\x12%\n" +
	"\x0egenerated_text\x18\x01 \x01(\tR\rgeneratedText\"Y\n" +
	"\rUpdateRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12-\n" +
	"\asegment\x18\x02 \x01(\v2\x13.story.StorySegmentR\asegment\"A\n" +
	"\x0eUpdateResponse\x12/\n" +
	"\bsegments\x18\x01 \x03(\v2\x13.story.StorySegmentR\bsegments2\xde\x01\n" +
	"\fStoryService\x12D\n" +
	"\x0fGenerateSegment\x12\x16.story.GenerateRequest\x1a\x17.story.GenerateResponse\"\x00\x12G\n" +
	"\x12StreamStoryUpdates\x12\x16.google.protobuf.Empty\x1a\x15.story.UpdateResponse\"\x000\x01\x12?\n" +
	"\rSubmitSegment\x12\x14.story.UpdateRequest\x1a\x16.google.protobuf.Empty\"\x00B2Z0github.com/SanishKumar/story-builder/proto/storyb\x06proto3"

var (
	file_proto_story_proto_rawDescOnce sync.Once
	file_proto_story_proto_rawDescData []byte
)

func file_proto_story_proto_rawDescGZIP() []byte {
	file_proto_story_proto_rawDescOnce.Do(func() {
		file_proto_story_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_story_proto_rawDesc), len(file_proto_story_proto_rawDesc)))
	})
	return file_proto_story_proto_rawDescData
}

var file_proto_story_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_story_proto_goTypes = []any{
	(*StorySegment)(nil),     // 0: story.StorySegment
	(*GenerateRequest)(nil),  // 1: story.GenerateRequest
	(*GenerateResponse)(nil), // 2: story.GenerateResponse
	(*UpdateRequest)(nil),    // 3: story.UpdateRequest
	(*UpdateResponse)(nil),   // 4: story.UpdateResponse
	(*emptypb.Empty)(nil),    // 5: google.protobuf.Empty
}
var file_proto_story_proto_depIdxs = []int32{
	0, // 0: story.UpdateRequest.segment:type_name -> story.StorySegment
	0, // 1: story.UpdateResponse.segments:type_name -> story.StorySegment
	1, // 2: story.StoryService.GenerateSegment:input_type -> story.GenerateRequest
	5, // 3: story.StoryService.StreamStoryUpdates:input_type -> google.protobuf.Empty
	3, // 4: story.StoryService.SubmitSegment:input_type -> story.UpdateRequest
	2, // 5: story.StoryService.GenerateSegment:output_type -> story.GenerateResponse
	4, // 6: story.StoryService.StreamStoryUpdates:output_type -> story.UpdateResponse
	5, // 7: story.StoryService.SubmitSegment:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_story_proto_init() }
func file_proto_story_proto_init() {
	if File_proto_story_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_story_proto_rawDesc), len(file_proto_story_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_story_proto_goTypes,
		DependencyIndexes: file_proto_story_proto_depIdxs,
		MessageInfos:      file_proto_story_proto_msgTypes,
	}.Build()
	File_proto_story_proto = out.File
	file_proto_story_proto_goTypes = nil
	file_proto_story_proto_depIdxs = nil
}
